# Generated by Django 4.2 on 2023-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('Zipcode', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.BigIntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.BooleanField()),
                ('sqft', models.BigIntegerField()),
                ('list_date', models.DateField()),
                ('photo_main', models.ImageField(upload_to='media')),
                ('photo_1', models.ImageField(upload_to='media')),
                ('photo_2', models.ImageField(upload_to='media')),
                ('photo_3', models.ImageField(upload_to='media')),
                ('photo_4', models.ImageField(upload_to='media')),
                ('photo_5', models.ImageField(upload_to='media')),
            ],
        ),
    ]
